"""EnterpriseDocumentClassifier.

Lightweight organization-specific classifier. Consumes forensic feature vectors
generated by DocuVerify's base forensic pipeline (app/services/pipeline.py) and
predicts organization-specific document risk.

This is a thin, honest wrapper around a scikit-learn estimator (Random Forest by
default; Logistic Regression as a fallback for very small datasets where a forest
tends to overfit) -- NOT a deep model, and NOT trained on raw pixels. It only ever
sees the same small, structured feature vector the base pipeline already computes
for every document, so it can be trained in seconds even on a laptop CPU.

Serialization: models are saved with joblib to a path this backend itself chose
(ml/models/enterprise_classifier.py never loads a path derived from user input,
and the ZIP upload path in dataset_service.py never contains a model file) -- see
SECURITY.md for why arbitrary pickle/joblib loading is otherwise unsafe.
"""
from __future__ import annotations

import datetime as dt
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any

import joblib
import numpy as np

# Stable feature schema: every EnterpriseDocumentClassifier, regardless of which
# organization/dataset trained it, consumes exactly these features in this order.
# Keeping the schema fixed (rather than dataset-dependent) means a model trained
# today stays compatible with the base pipeline's output tomorrow.
FEATURE_SCHEMA: list[str] = [
    "visual_anomaly",
    "typography_anomaly",
    "layout_anomaly",
    "metadata_anomaly",
    "semantic_anomaly",
    "ocr_confidence_mean",
    "ocr_word_count_norm",
    "region_anomaly_count_norm",
    "high_severity_region_count_norm",
]


@dataclass
class TrainedModelMetrics:
    accuracy: float
    precision: float
    recall: float
    f1: float
    roc_auc: float | None
    train_size: int
    val_size: int
    test_size: int


@dataclass
class EnterpriseDocumentClassifier:
    """Wraps a fitted sklearn estimator plus the metadata needed to use and audit it."""
    estimator: Any
    algorithm: str
    feature_schema: list[str] = field(default_factory=lambda: list(FEATURE_SCHEMA))
    trained_at: str = field(default_factory=lambda: dt.datetime.utcnow().isoformat())

    def predict_risk(self, features: dict[str, float]) -> float:
        """Returns a 0-1 organization-model risk score for one document's feature vector."""
        x = np.array([[features.get(k, 0.0) for k in self.feature_schema]])
        proba = self.estimator.predict_proba(x)[0]
        # class 1 == "forged" by convention (see dataset_loader.py's label encoding)
        classes = list(self.estimator.classes_)
        return float(proba[classes.index(1)]) if 1 in classes else float(proba[-1])

    def save(self, path: Path) -> None:
        path.parent.mkdir(parents=True, exist_ok=True)
        joblib.dump(self, path)

    @staticmethod
    def load(path: Path) -> "EnterpriseDocumentClassifier":
        return joblib.load(path)
